### ISSUE TITLE
info button doesn't work when OSD disabled

### ISSUE THREAD

**Issue by ghost** [marqs85/ossc#112]
Hello, 
So as not to have the OSD info keep coming up on the screen during games that switch resolution a lot during game, eg. Dead or alive, then the only way seems to be settings OSD status display to off? But when doing that it also stops you from being able to manually check the screen status / resolution using the info button. You should still be able to manually check the display info / resolution by pressing the info button on the remote but you can't access that info

**Comment by marqs85** [comment]
Ossc Pro v0.77 just added a menu option to display a sticky info window, but code space on original OSSC is fully utilized so this won't make it there.

**Comment by ghost** [comment]
Seems ridiculous that you can't manually display resolution info on the screen even with automatic OSD off, you don't want it keep displaying frequent resolution changes on the screen while playing games such as Dead or Alive do you? Is there any work around? 

How about changing it so you can have an OSD info setting of 0 seconds instead of off? Then you could manually press it on when you want? That would resolve the problem I think

**Comment by marqs85** [comment]
It's not about the request being unjustified, but preserving existing functionality (when OSD is enabled) and adding special treatment when OSD is off would require extra code space, i.e. removal of some other features. Even making it sticky in all OSD modes would require spending hours on optimizing some bytes free elsewhere, and not everyone would like the changed behaviour in the end.

**Comment by ghost** [comment]
yes, I said you can add a setting that is: OSD info **0 seconds**, rather than "off", then it won't automatically display OSD upon resolution changes unless you manually display it, but doesn't have to be fully turned off so resolution info OSD is still manually accessible
the option of "off" doesn't need to be there, just have a 0 seconds option instead, the OSD duration code is already there
