### ISSUE TITLE
GBI 240x360 Line3x artefacts on 1.10 (regression from 1.09)

### ISSUE THREAD

**Issue by AuroraWright** [marqs85/ossc#116]
I noticed on 1.10 GBI is artefacting in Line3x/1080p while it was fine on 1.09. This also happens with settings reset to default with both firmwares, except for adjusting sampling phase and changing 384p/400p to Line3x 240x360.
Samples attached captured with an elgato capture card (look at the grass in the first sample and the letters next to the green square in the second one)
1.09:

https://github.com/marqs85/ossc/assets/15571693/87916c5e-b56f-4d67-929a-6a60bcff87ff

https://github.com/marqs85/ossc/assets/15571693/1d0a7a47-ba89-41bf-8cbf-80fe83251b9a

1.10:

https://github.com/marqs85/ossc/assets/15571693/cccc9e53-3fd4-4533-8e41-9cec65955de1

https://github.com/marqs85/ossc/assets/15571693/13554a8a-89b4-4b25-a4dc-7bd95ffeb27d

**Comment by marqs85** [comment]
Workaround added in 8ef05364b455367ed607c2c667ad0df0305c857f
