### ISSUE TITLE
Question: How to find out which firmware to use?

### ISSUE THREAD

**Issue by Andiweli** [marqs85/ossc#121]
It is a OSSC KAIKO Edition, no idea what firmware is installed currently, bought 2 years ago.

![IMG_2759](https://github.com/user-attachments/assets/635ec7a0-c2cc-4deb-bcb7-ec45e7a02883)

**Comment by marqs85** [comment]
Change "Settings -> "Initial input" to test pattern, save profile and power cycle the device. Please also use support forum or manufacturer's materials for general usage questions in future.
