### ISSUE TITLE
Feature Request: 400p PC mode with Line2x and Line3x

### ISSUE THREAD

**Issue by James-F2** [marqs85/ossc#29]
Greetings Marqs.

CRT and 4:3 LCD (w/VGA input) monitors are becoming rare, and I think the OSSC can do great job for supporting retro PCs.
I see more and more retro gamers and youtubers using the OSSC with their DOS machines resulting in ugly image, form the lack of dedicated and tuned default 400p mode.

Currently the OSSC lacks a proper 400p mode support for retro (DOS) computers that output 720x400 text mode as native resolution via VGA.
The OSSC handles 400p resolutions in the 384p menu (confusing) and lacks a much needed Line3x.
Proper 4:3 aspect ratio can be achieved by adjusting the Samplerate and lowering Active pixels, but Line2x is simply not enough sampling rate (w/upsample2x) for smooth pixels with native 720 horizontal resolution so the pixels are deformed, that's why Line3x is much needed in 720x400p modes.

Current 640x400 need to be renamed to 720x400 and default timing need to be changed as in the link below, it will produce pixel accurate (native) image over HDMI like connecting directly to a monitor with VGA cable, but will not result in 4:3 image on 16:9 monitors even with "aspect" turned On in monitor settings.
To produce a 4:3 image, a custom timing with Line2x or Line3x is needed with lowering the active pixels.
Further info I've posted on VGP forum:
https://www.videogameperfection.com/forums/topic/400p-mode-for-retro-pc/#post-27188

I hope too see more love for 400p mode and DOS gaming on the OSSC.

Thank you,
James

**Comment by James-F2** [comment]
You were right.
640x400 and 720x400 have different clocks form my retro video cards.
I used a 320x200 (640x400) grid test pattern and it looked pixel accurate only with 800 samplerate, most if not all games use this.
Text mode 720x400 only looks pixel aligned with 900 samplerate.

Lin3x 1600x1200 would greatly help with low sampling rate and deformed pixel in 4:3 image.
I'm wondering if something can be done with Line2x to help produce 4:3 image in the standard 1280x800 resolution or 1066x800 (4:3) with the lower sampling rate?
Thank you again for looking into this.

**Comment by marqs85** [comment]
400p support improved in 4a686da.
