### ISSUE TITLE
Keep presets after firmware update

### ISSUE THREAD

**Issue by fredhgl** [marqs85/ossc#32]
After a firmware update, my ossc lose all presets.
Can you develop a method not to lost these presets?
Thank you in advance.

**Comment by marqs85** [comment]
Developing a robust method for parsing settings from past/future firmwares would most likely consume remaining block RAM from FPGA. Fortunately there is a web app that can be used for saving/converting settings for different fw, see the forum [thread](https://www.videogameperfection.com/forums/topic/profile-settings-web-app/).
