### ISSUE TITLE
Firmware 0.85

### ISSUE THREAD

**Issue by Sirethief2525** [marqs85/ossc#35]
Hey, I was wondering if somebody would be able to help with getting the sd image for the .85 that is there now for testing purposes, I have a slightly older jtag file but my programmer is garbage. if anybody could help me out that'd be great, thank-you in advanced. I guess I should've used this box first

**Comment by Sirethief2525** [comment]
Hey, I was wondering if somebody would be able to help with getting the sd image for the .85 that is there now for testing purposes, I have a slightly older jtag file but my programmer is garbage. if anybody could help me out that'd be great, thank-you in advanced.

**Comment by marqs85** [comment]
0.85 is now publicly available for download
