### ISSUE TITLE
Cyclone V compatibility

### ISSUE THREAD

**Issue by ArnoldDeRuiter** [marqs85/ossc#48]
Since I would like to start using a OSSC but also want the OSSC Pro, Quartus Prime Lite Edition is compatible, but is the current OSSC software capable of running compatible on a Cyclone V?

Perchance there is already a OSSC Pro development image out there to try, but I haven't seen it myself.

**Comment by marqs85** [comment]
There's not much Cyclone IV specific code, PLL configuration is probably the only notable thing that would need some porting work. However, I wouldn't recommend starting from OSSC code here but to look into [DExx-vd_isl](https://github.com/marqs85/DExx-vd_isl) repository which has much of the core code rewritten and targeted for a couple Cyclone IV/V development boards. That project is still very much in progress but it should be much better starting point.
