### ISSUE TITLE
Firmware 0.76 (no matter with/without audio or JP) starts sometimes from second time

### ISSUE THREAD

**Issue by alfishe** [marqs85/ossc#5]
Issue appeared in 0.76 only. Backlight turned on but no menu displayed once in a while for turning on. Powering off and on again fixes the issue.
There was no such effect in previous versions including 0.75

**Comment by marqs85** [comment]
Does that only occur with JP firmware? I haven't noticed anything similar on EN firmware versions.

**Comment by alfishe** [comment]
Yes, seems that I've built JP+Audio version first and it had startup issues. Then recompiled to EN+Audio and no issues since then

**Comment by marqs85** [comment]
Cannot reproduce with latest code.
