### ISSUE TITLE
Vsync problem, Screen tearing every few seconds

### ISSUE THREAD

**Issue by ghost** [marqs85/ossc#53]
Hello
There is a problem with Vsync and every few seconds on the screen update I get a screen tear, it's most noticeable on scrolling games but I've noticed it on sprites too, my Mega Drive is NTSC running at around 59.8hz I think.
The monitor supports 56-75hz

**Comment by marqs85** [comment]
You should be adjust position via Sampling Opt->Adv Timing->H/V backporch

**Comment by filevans** [comment]
Do you know why my monitor won't allow adjustment with the OSSC connected? Brightness/contrast and all geometry is greyed out, I'm using HDMI to DVI as my monitors don't have HDMI. On the other monitor I get "out of range", and also after changing all the back porch and sample length settings, I lost all the settings when I tuned the OSSC off and back on again, so it doesn't save the settings?

**Comment by marqs85** [comment]
OSSC runs with a fixed line buffer so its output cannot tear in the traditional sense. Judder is periodically seen on displays which don't frame lock into the incoming frequency. I'm pretty sure the problem is with display (which mark&model?), you could try another one if possible to verify that.

**Comment by ghost** [comment]
Yes it only happens on one monitor 
https://iiyama.com/us_en/products/prolite-e2607wsd-1/

It doesn't happen on any other TV or monitor I tried.  Well it's annoying as I wanted to use my 16:10 monitor it has a much better height than 
16:9
