### ISSUE TITLE
Feature request: swap green and blue RCA digitally

### ISSUE THREAD

**Issue by omikron24** [marqs85/ossc#54]
For whatever reason component RCA order is RGB which is incorrect. The correct format is RBG. This design mistake causes unnecessary cable twist and strain. I could re-solder color connectors however I can't swap the digital processing hence the request. 

Could you please add the option to the "Compatibility" sub menu to swap Green and Blue RCA channels?

**Comment by marqs85** [comment]
Unfortunately G/Y line carries sync so the signal path is different and cannot be exchanged with R or B lines. As for why the connector has such order, suitably sized 3xRCA connector part with YPbPr order was not found during design time. The input can also be used for RGsB so it's not exclusively for YPbPr.

**Comment by omikron24** [comment]
Will the same issue affect OSSC pro model?

**Comment by marqs85** [comment]
Depends whether we can find a suitable 3xRCA connector block with YPbPr color order this time, their availability is not that good these days.

**Comment by alanbork** [comment]
the current order never bothered me. You'd have to have a pretty degenerate
cable for it to matter, I think.

**Comment by omikron24** [comment]
> 
> the current order never bothered me. You'd have to have a pretty degenerate cable for it to matter, I think.
>

They are official nintendo cables

**Comment by omikron24** [comment]
> 
> 
> Depends whether we can find a suitable 3xRCA connector block with YPbPr color order this time, their availability is not that good these days.

Let me help you with this one as I have the power of google! Jokes aside, I'm not affiliated with any company that makes these but here are some links that may be useful later:

[5 RCA jack](https://hk-rmt.en.made-in-china.com/productimage/eKSxBAwvyXkI-2f1j00rFzTumGyCHoM/China-AV-Jack-Pin-Jack-RCA-Jack-AV5-8-4-59-.html)

[5 RCA jack another](http://www.mfg-components.com/AV%20Pin%20Jack-AC%20Power%20socket-Wire%20to%20Wire%20Connector-Scart%20Socket-Mini%20Din%20Connector/LZ-AV5-01CPK-RCA-CONNECTOR)

Or, single connectors with appropriate colors:
[Single colored RCA](https://eu.mouser.com/Search/Refine?N=4246260295&Keyword=rca&No=25&FS=True)

But thank you for your replies! Much appreciated

**Comment by marqs85** [comment]
Closing the issue since digital swap not possible on the current HW.
