### ISSUE TITLE
What toolchain do you use? Can we get a 'getting started' guide?

### ISSUE THREAD

**Issue by renegadeandy** [marqs85/ossc#6]
Hi everyone, 

I would like to get started with adding some features or at least trying to understand the code flow for this project. Additionally, it would be nice to understand how to, having made a change, hookup a programmer to the board and apply the new firmware to the device (even if it is just compiling the project to a bin and copying this to the sd card).

I know it will be on the list of 'to do' but can you please write the readme.md and give others a chance at getting started with the software side of this project?

**Comment by marqs85** [comment]
Yeah, it's been on todo-list far too long. Basic build/install instructions are now added on README.
