### ISSUE TITLE
Dreamcast cut off mode

### ISSUE THREAD

**Issue by arromdee** [marqs85/ossc#63]
My TV is an Element TV which will, whether I want it to or not, zoom when the TV is set to 4:3 and the OSSC outputs certain modes.  It appears that it does not zoom in 1280x960 mode (such as I get with 4x from a 240p source), but it *does* zoom in 720x480 (Dreamcast with DTV input) and in 1440x960 mode (Dreamcast with DTV imput, and Line2x).

It does not zoom in 640x480 or 1280x960 mode with Dreamcast at Vesa 480p, but of course that mode produces the wrong aspect.  If I try adjusting the sampling rate from that to try to force the aspect to be correct anyway, and I adjust the sample rate too far away form 800, the TV 1) claims it is 1263x960 or some other weird number that is not 1280, and 2) suddenly starts zooming. 

So I *believe* that I can get Dreamcast to work perfectly if there is such a mode as "Dreamcast DTV input sampled at 858, then cut off the black area and produce an output which is 640x480 (1280x960 with Line2x).  I have no way to be certain, of course, unless it exists and I can try it, but I'm requesting that such a mode be added.

**Comment by marqs85** [comment]
You can try reducing H.active in DTV 480p mode, but the TV may not like that either.
