### ISSUE TITLE
Is it possible to modify the firmware to output at 640@480@120Hz?

### ISSUE THREAD

**Issue by QUAKEULUS** [marqs85/ossc#66]
I'm interested in using console>ossc>hdmi2vga>PC crt 

and since most PC crts ahve no problem doing 120Hz, can OSSC firmware be modified to output at 120Hz isntead of its usual 60?

What problems are obviously presented by this?

**Comment by marqs85** [comment]
Framedoubling is not possible without a frame buffer. You should be looking for the upcoming Pro model for this feature.

**Comment by QUAKEULUS** [comment]
Is this a planned feature for the pro?
