### ISSUE TITLE
Maximum Line Buffer?

### ISSUE THREAD

**Issue by WNKLER** [marqs85/ossc#68]
How many lines can the current hardware buffer?

I'm interested in framing 525p (480 active) content in a 562p (540 active) window.

I think this can be done by buffering as few as 36 lines.
After buffering about 36 lines at 31.5 kHz, they could be scanned out at a rate of 33.75 kHz.
Since the buffer is emptying faster than being filled, the number of lines buffered would slowly decrease to zero until 525 have been drawn.
Then the buffer would grow back up to 36 lines before repeating.

Ultimately the goal is to display content in a stable 540p (or also 1080p if possible) window with as little lag as possible.
Does this sound possible?

**Comment by marqs85** [comment]
OSSC has 2-line buffer of max. 2048 samples per line. You need to look into OSSC Pro (or its DIY sister [project](https://github.com/marqs85/DExx-vd_isl)) which have enough block RAM and clock generator to implement the things you mentioned.
