### ISSUE TITLE
[Feature request] Improve the "INFO" button (make it a toggle)

### ISSUE THREAD

**Issue by RowanDDR** [marqs85/ossc#69]
When you press "INFO" button, info comes up... but it stays up forever.. no timeout. At the moment I think the only way to clear the info box from the screen is to press "MENU" then exit out of the menu, which is not intuitive.

So I propose 2 improvements:
- Make pressing "INFO" clear the info box, if its currently displayed.
- Give the "INFO" box a timeout of say ~10 seconds.

**Comment by marqs85** [comment]
9c5e7b5 already implements more extensive info box which is shown for the duration of OSD status disp.

**Comment by RowanDDR** [comment]
OK thanks, good to know. Good work!
