### ISSUE TITLE
31kHz 640p VGA signal seems to be upscaled to some non very standard resolution for HDMI

### ISSUE THREAD

**Issue by alfishe** [marqs85/ossc#8]
More a question rather than an issue.
Have 31kHz 640p VGA signal from ZX Evolution board. OSSC detects input signal properly and displays something to HDMI, but that something cannot be decoded by my Sony Bravia 1080p TV.

Is there a way to change output resolution or ideally - have always 1080p FullHD signal on output?

**Comment by marqs85** [comment]
Please use VGP [forums](https://www.videogameperfection.com/forums/forum/ossc/) for source-related compatibility discussion.

Due to operation principle output mode is always dependant on input (e.g. identical refresh rate), so it's not possible to always output spec-compatible 1080p.
