### ISSUE TITLE
The OSSC menu doesn't resize properly on some display modes.

### ISSUE THREAD

**Issue by ghost** [marqs85/ossc#81]
The OSSC menu doesn't resize properly on some display modes.

I was using a 480i PS2 game as an example. On passthrough mode, the menu gets extremely squished and small, compared to its normal size on the other 2x, 3x, or 4x modes. It also makes it extremely hard to use and see the text. I'm using a 24" BenQ 1080p IPS monitor. 

I'm unsure if this affects the menu size, but I also have PS2 optimal settings tuned in. Per the wiki, this would be the following for the PS2:
H.active=640, H.synclen=44, H.backporch=116

Again, the other 2x, 3x, or 4x modes display the menu all the correct size. Let me know if you need any more specifics.

Thanks

**Comment by marqs85** [comment]
Fixed in cbe2611
