### ISSUE TITLE
PC-9821 over 24Khz does not look properly

### ISSUE THREAD

**Issue by gameblabla** [marqs85/ossc#83]
Hello,
just wanted to report that 24Khz VGA output on my PC-9821 Nr15 does work but it seems that its resolution is being mis-detected and as result, looks pretty bad.
It's possible to boot in 31Khz mode by pressing Grph + 2 on boot but this disables the internal LCD and some games switch back to 24Khz anyway.

Here's a couple of screenshots taken from my USB capture card with my OSSC connected to it :
![24khz_1](https://user-images.githubusercontent.com/8717966/111375392-162a0100-8696-11eb-83ec-ac5d048c8cb4.png)
![24khz_2](https://user-images.githubusercontent.com/8717966/111375398-1924f180-8696-11eb-8c2a-c8c5764a39b4.png)
![24khz_3](https://user-images.githubusercontent.com/8717966/111375411-1cb87880-8696-11eb-9064-4e10239daba0.png)
![24khz_4](https://user-images.githubusercontent.com/8717966/111375415-1de9a580-8696-11eb-9211-9884f0d63344.png)

And this is how 31Khz looks like (and how 24khz should look like too)
![31khz_1](https://user-images.githubusercontent.com/8717966/111375460-2c37c180-8696-11eb-9675-e61ed1c12e66.png)
![31khz_2](https://user-images.githubusercontent.com/8717966/111375462-2d68ee80-8696-11eb-878f-613e320fad8b.png)
![31khz_3](https://user-images.githubusercontent.com/8717966/111375466-2e018500-8696-11eb-8f1b-609519f19d9e.png)
![31khz_4](https://user-images.githubusercontent.com/8717966/111375470-2e9a1b80-8696-11eb-92f2-f9d81e57a66f.png)

Notice the extra black pixels on the right and the bottom getting cropped in Doom 2.

**Comment by marqs85** [comment]
Which firmware version are you using? I think some of the PC98 related mode presets got broken in 0.87 (more specifically in b26b213), but they should be now fixed by 2e7141c but it's not yet in official firmware. You might try if v0.86 works until a new fw is released.

**Comment by gameblabla** [comment]
> Which firmware version are you using? I think some of the PC98 related mode presets got broken in 0.87 (more specifically in [b26b213](https://github.com/marqs85/ossc/commit/b26b213ead6b3c6a2c79acd97a78b15b56cd698c)), but they should be now fixed by [2e7141c](https://github.com/marqs85/ossc/commit/2e7141c3b2798c3872c7f460db6eb71dadf4f00c) but it's not yet in official firmware. You might try if v0.86 works until a new fw is released.

I'm using 0.88a which seems to predate your commit. I'll see if i can compile it from scratch, if not i'll revert back to 0.86. Thanks

**Comment by gameblabla** [comment]
Well Quartus is 7Gb+ so yeah, looks like i won't be able to compile it from source. :/ (If someone could compile me a nightly build, that would be nice)

Flashed 0.86a instead to see what it was like and it's not quite right either.

![new24kz_1](https://user-images.githubusercontent.com/8717966/111391870-5cd72580-86ad-11eb-91e6-d56ab9b76d89.png)
![new24kz_2](https://user-images.githubusercontent.com/8717966/111391872-5e085280-86ad-11eb-8fe5-ca2e6e7db6f3.png)
![new24kz_3](https://user-images.githubusercontent.com/8717966/111391876-5fd21600-86ad-11eb-8a2d-4d28bc40b7cd.png)
![new24kz_4](https://user-images.githubusercontent.com/8717966/111391878-5fd21600-86ad-11eb-8bc8-5018ad79ef8a.png)

Part of the screen on the left is cropped off and there are still black bars on the right. It does fix the bottom getting cropped up though.

**Comment by marqs85** [comment]
You can adjust horizontal position by tweaking H.backporch in Sampling Opt->Adv. timing.

**Comment by gameblabla** [comment]
Have somewhat decent picture with these settings :
H.samplerate = 848.0
H.synclen = 99
H. backporch = 49
V. synclen = 1
V.active = 400

![wavy](https://user-images.githubusercontent.com/8717966/111394755-3d42fb80-86b3-11eb-91d8-c64b65d91e39.png)

It still looks worse than 31Khz though (i have wavy lines all over the screen) but perhaps that's because my VGA cable is not well shielded ?

**Comment by marqs85** [comment]
Closing the the primary issue is fixed in 2e7141c.
