### ISSUE TITLE
[Question] - Locating/editing startup grayscale pattern

### ISSUE THREAD

**Issue by j-schoch** [marqs85/ossc#87]
Hello,

I'm poking around the repo and trying to locate where/how the default grayscale screen is displayed.

My goal is to edit this screen to simply display something else, any clues or guidance would be appreciated.

![grayscale](https://user-images.githubusercontent.com/5287619/137054182-637de48c-bfd3-49c3-b8f7-eeb66aaf0800.png)

**Comment by marqs85** [comment]
It's generated [here](https://github.com/marqs85/ossc/blob/release/rtl/videogen.v#L140).

**Comment by j-schoch** [comment]
Thank you!
