### ISSUE TITLE
Capture card doesn`t show resolutions above 480p correctly

### ISSUE THREAD

**Issue by AlivE-git** [marqs85/ossc#88]
I have chinese capture card "rullz u3". Yesterday I tested it with gbs-control, and resolutions above 480p work corretly. But my ossc shows this picture in 480p line2x mode. It shows the first quadrant on the picture. Second screenshot shows the same game sceen but in a 480p. I tried with the same capture card pc resolutions such as 960p. It shows correctly.
Maybe ossc gives not standart hdmi signal or doesn`t give some metadata?
![obs64_2021-11-14_18-01-40](https://user-images.githubusercontent.com/12865205/141817822-d970b924-e079-4ada-b158-b9098201f177.png)
![obs64_2021-11-14_18-01-47](https://user-images.githubusercontent.com/12865205/141817829-aeccbc8b-cd36-459c-bd94-840b1ca8de5d.png)

**Comment by marqs85** [comment]
You can try the following:

1. Enable Sampling opt.->Allow upsample2x (disables HDMI pixel repetition)
2. Set Compatibility->Default HDMI VIC to 2 (indicates 480p60, might help with some badly designed sinks)
3. Set Output opt.->TX mode to DVI (disables all HDMI metadata)

**Comment by AlivE-git** [comment]
Unfortunately it didn't help.
For the test I tried changing the "480p in sampler" values ​​between "DTV 480p" and "VESA", and the capture card changes the screen resolution (720x480 and 640x480), but it is still "cropped" in x2 mode.

**Comment by marqs85** [comment]
If it doesn't work even in DVI mode, then I'm afraid the card just doesn't recognize/support 480pX2 timings. You can try enabling Compatibility->Full TX Setup before changing to the mode and reset the card in OBS. Are the any control options for the card and does it show any detailed information about the signal?

**Comment by AlivE-git** [comment]
There are no additional settings, even the resolution is configured in hardware, I can only select the current one in obs.
mjpeg doesn't show any useful information. Maybe there is some kind of program...
![image](https://user-images.githubusercontent.com/12865205/142024620-11cdd343-161f-4531-905e-def684064609.png)
![image](https://user-images.githubusercontent.com/12865205/142024688-09dcfbcc-f414-46da-96b8-8ed65d542d7a.png)

**Comment by marqs85** [comment]
Perhaps the card only supports standard CEA/VESA timings. That would explain why VESA 960p via PC worked. You could confirm this by testing a custom PC modelines such as below:

Horizontal active: 1440
Horizontal front porch: 32
Horizontal sync width: 124
Horizontal total: 1716
Horizontal sync polarity: –

Vertical active: 960
Vertical front porch: 18
Vertical sync width: 12
Vertical total: 1050
Vertical sync polarity: –

Pixel clock: 108MHz

**Comment by AlivE-git** [comment]
Yep, same problem. Thanks for the explanation. It seems impossible to find a cheap card with good compatibility
![obs64_2021-11-29_18-54-46](https://user-images.githubusercontent.com/12865205/143900985-733909c6-f18e-4b2e-81ed-508c214c8035.png)
.
