### ISSUE TITLE
Trying to install firmware via JTAG USB Blaster

### ISSUE THREAD

**Issue by Cuber445** [marqs85/ossc#92]
I am very new to FPGA programming but I've encountered an issue. I'm aiming to install new firmware via JTAG but do not have appropriate files.  I'm looking to convert the .cof file into a .jic, but when i try to open the file in "Convert programming file" I get an error saying "Can't locate programming file ossc.sof (in output_files/&) in Conversion Setup File". How can I go about solving this?

**Comment by Cuber445** [comment]
I think I'm just having an issue generating the .sof file. When i open the project I can't seem to compile even the available firmware as i get a warning saying "Script File sys/sysnthesis/sys.qip not found"

**Comment by marqs85** [comment]
You have to build qsys output files first - see "Building RTL (bitstream)" section on the README on root. Pre-generated .jic files are also available [here](http://www.infocult.com/m/ossc/fw/jtag_prog/).
