### ISSUE TITLE
Not saving H Backporch on 1080p

### ISSUE THREAD

**Issue by ghost** [marqs85/ossc#96]
Hello, I keep setting H Backporch to 130 and then save it in settings under profile 0 and 1 but when I turn the OSSC back on, the H Backporch has gone back to 148. It only seems to be happening on 1080p and not on other resolutions, not sure if this is a bug with the firmware and if I need to update firmware?
Thank you

**Comment by marqs85** [comment]
I recall this was an issue with some older firmware, you should definitely try the latest.

**Comment by marqs85** [comment]
Instructions are shown both on the character display and monitor up to the point where the actual update starts. After that status is shown on the character display only.

**Comment by ghost** [comment]
Yes but my old firmware didn't have any OSD, anyway the new firmware update has fixed the problem, the settings are being saved! And I really like the OSD too, thanks!!
