### ISSUE TITLE
Amiga 768p resolution through AV3 not supported through OSSC 1.6 upscaler.

### ISSUE THREAD

**Issue by Tallguy297** [marqs85/ossc#98]
I have a Commodore Amiga 600 plugged from the RGB port to the OSSC AV1 using a SCART cable.
The Vampire 2.2 accelerator output HDMI plugged into the AV3 using a VGA Cable and UGreen adapter. (see image)
I have configured the OSSC to auto detect inputs.
This is handy for switching screen modes from ECS to RGB automatically when there is a loss of sync on one of the outputs.

The latest 0.90 firmware has been installed.

The problem I have is that the AV3 input does not seem to support 1024 x 768 or 1360 x 768 screen resolutions.
The maximum mode it seems to handle is 1280 x 720.
If I plug the HDMI output of the Vampire 2.2 directly into my monitor, both 1024 x 768 and 1360 x 768 are supported.
However I cannot auto-switch between screen modes. It's a bit of a pain in the neck.

Is there a solution?

Thank you.

![Kit](https://user-images.githubusercontent.com/49935683/180687790-037549dc-905e-4660-ae4b-3214f64c8f40.jpg)

**Comment by marqs85** [comment]
Does the character LCD say NO SYNC when you output those resolutions or are there any signs it's trying to sync? At least 1024 x 768 (60Hz?) should be detected correctly if it's using timings similar to VESA.

**Comment by Tallguy297** [comment]
No it doesn't show a NOSYNC.
It shows the resolution on the LCD display as 790p.
I tried the 1024 x 768 preset, but could not get a picture.
I double checked my monitor resolutions.
I have a TOSHIBA 19DV615Y TV monitor.

![Image1](https://user-images.githubusercontent.com/49935683/181192738-2e917655-e404-4f44-850e-495f9cbfd955.jpg)

Perhaps there is a setting that can be changed, but I don't know which one?

Thank you...

**Comment by marqs85** [comment]
790 lines is a bit off the VESA XGA 60Hz standard (806 lines), but it should be still pick the 1024x768 preset (you can verify this by pressing the INFO key on remote). If the mode works when directly connected to monitor, then it should be just matter of adjusting sync/backporch (via Adv. Timing menu) of regenerated signal to match the source. Is there any information of the exact timings output by Vampire 2.2?

**Comment by marqs85** [comment]
Actually, if the output is 790 lines, then I think the issue is with the default V. backporch 29 which is too much. Try reducing that to e.g. 10 via the Adv. Timing menu.

**Comment by Tallguy297** [comment]
Unfortunately the Apollo Team has not been forthcoming with information on timings on the HDMI output of the Vampire 2.2 accelerator card.
I am using standard timings using the CVT utility from Aminet (https://aminet.net/package/driver/video/cvt12) and using the Picasso96TNG tool to provide preferences.

I am not an expert on the OSSC. Is there a preset I can download to test out the 768p on AV3?

In the meantime, I will have a go at implementing your settings and send you the results.

Thanks for you help.
Alexander.

**Comment by marqs85** [comment]
The sampling preset on OSSC is selected automatically based on number on input lines etc. While it's not possible to force another preset, you can freely edit timings of the selected preset. In this case it should be enough to reduce V. backporch to 10.

**Comment by Tallguy297** [comment]
`Actually, if the output is 790 lines, then I think the issue is with the default V. backporch 29 which is too much. Try reducing that to e.g. 10 via the Adv. Timing menu.`
I tried that and worked.
I also mucked around with the settings for the other resolutions and manage to fix up my problems.

Many thanks for your advice.
Much appreciated.

Thank you,
Alexander.
